### ISSUE TITLE
Adding a review page

### ISSUE THREAD

**Issue by Fairspy** [Praful932/Kitabe#171]
**Is your feature request related to a problem? Please describe.**
I would like to add a page where  users can write reviews for the books read by them.

**Describe the solution you'd like**
I would like to add a button in the book modal called review which would then lead to a separate page to the user where they can add a new review for the book if logged in or browse through the existing reviews.

**Are you willing to contribute to this issue?** 
Yes, I am willing to contribute to the issue as a gssoc'21 participant.

**Describe alternatives you've considered**
None

**Additional context**
I feel that reviews play a key role when a user is looking for a particular book and thus would like to Implement the same.

**Comment by maneprajakta** [comment]
I don't think there is need for this what you say @Praful932

**Comment by Praful932** [comment]
I don't think we would be needing an implementation for this,currently we want to focus on fixing bugs and **high priority issues**. We do feel the need for a discussions section instead of a review in a future release tho :)
We will open new issues as soon as current milestone is finished.
Closing for now
