### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by Sudhir-Pawar** [Praful932/Kitabe#19]
Hi I really liked the idea of the book recommendation system and project that you have built so far. I also visited your project website. It looks really nice.
Some suggestion for improvement:
1.  I notice that you have used a lot of carousels, well it looks good at first but it's difficult to use at least for me when I  was exploring your explore page and your home page genre session. I would like it more if new books are added as I scroll down on the explore page. For genre sessions I would recommend showing it all in grid view in your home page.
2.  Color scheme can be improved. There are many website that you can use like [coolors.co](https://coolors.co/) or [colorhunt.co](https://colorhunt.co/).
3.  For some book cards where author name and book name are long they overlap the rate this button and more details button. You can tackle this by defining a fix size for author name and book name sessions for each bookcard and crop the rest of part if it does not fit in the defined size replacing it with ... .

Regards,
Sudhir

**Comment by maneprajakta** [comment]
Hi @Sudhir-Pawar 
Thank you for visiting the project and giving Feedback.
for  your suggestions:
1.We have lots of books to show in the Explore section that's why we made carousel for it. We will try but if it's giving the user a friendly way to operate the website.
2.This will be solved by issue #13 we are working on it.
3.Can you specify in which section this happens.
Also if you want to take any of this issue you are welcomed to contribute :smile:

**Comment by Sudhir-Pawar** [comment]
For bookcard where bookname and authorname  are long overlap with ratethis and more details button happens in "Popular Among Us" section on Home page.

**Comment by maneprajakta** [comment]
ok thanks @Sudhir-Pawar

**Comment by Praful932** [comment]
#26 Fixes this
