### ISSUE TITLE
Add a Contact Us page.

### ISSUE THREAD

**Issue by Surabhi0910** [Praful932/Kitabe#45]
**Is your feature request related to a problem? Please describe.**
A contact us page is a must for any site. How else are people going to get in touch with you. I think this an important feature that must be included.

**Describe the solution you'd like**
Hence, to solve the above problem. I would like to develop a contact us page for everyone using this site.

**Are you willing to contribute to this issue?** [Yes/No]
Yes.

**Describe alternatives you've considered**
If not a page, a contact us/get in touch popup could also suffice the need.

**Additional context**

**Comment by vidhi1121** [comment]
i want to work with this project under Gssoc'21

**Comment by maneprajakta** [comment]
@Surabhi0910 Can you please follow the Issue template.
I have updated the issue description. Please make changes accordingly.

**Comment by Surabhi0910** [comment]
@maneprajakta I have updated. Could you please have a look at it now?

**Comment by chandramanipandey** [comment]
@Surabhi0910 

Hi there Mentors, I am participant of GSSOC 21, I would like to work on this issue with the project Given below is my proposal.

A contact us page is usefull for connecting users of the app to connect with the company in most of the ways possible, In my view there are 3 ways i will make this possible
1)Phone no for technical support (Old way but this could be replaced by live chat with technical experts )
2)Contact us form (This will send an mail to website admin regarding user issue or if buisnesses wants to connect with them)
3)Social media platform links (To help users connect with us and get updated about our new products on our facebook or instagram pages )
4)Google maps API (IF required by you)

However in addition to this there are many things that make up a contact us page , As i described this page is made to help users with there problems or to connect buisnesses with us 
-So this page will have an FAQ bootstrap card
-Checkbox if clicked user will receive news and updates via email
-A little information about the company and there leaders

I could add these features to the contact us page , Also can you let me know if this issue comes under GSSOC 21 label because it was raised recently but i could not see any GSSOC label.

**Comment by Praful932** [comment]
Hi @shubhamgoel01 @chandramanipandey @Surabhi0910 @kanchi-22 Appreciate your interest in the project and for going all out on this issue 🙂
We already have a footer if anyone wants to be able to contact us or check out the repository
![image](https://user-images.githubusercontent.com/45713796/110587810-1dcf3e80-819a-11eb-9b17-b6bcda9289fc.png)

Since our intention of this project is as a community platform, for people who like books to browse and get recommended books that they may like, rather not as a business which would offer services and would have a specific contact us page/Tech support.
If you have any other ideas, feel free to create an issue or check out the [starter guide](https://github.com/Praful932/Kitabe/discussions/42)

Thanks, 
Praful
