### ISSUE TITLE
New Feature : Wishlist

### ISSUE THREAD

**Issue by Miru-s** [Praful932/Kitabe#56]
**Is your feature request related to a problem? Please describe.**
Wishlist or a save for later feature where one can save their favorite books for later.
Ex: When a person is randomly browsing through the website and comes across a book of his/her interest but is already preoccupied by other things and wants to keep it for later can use this feature to save the book in his/her "to read list".

**Describe the solution you'd like**
Just like web browsers have bookmark option, e-commerce websites have wish list option to have a collection of their favorite stuffs, a similar feature must be added to the Kitabe to save people's time of looking up for same book again and again.

**Are you willing to contribute to this issue?** 
Yes, I am willing to contribute to this issue as a participant in Gssoc'21.

**Describe alternatives you've considered**
I thought of adding a "recently viewed" section.

**Additional context**
As a avid book reader i always look up for new books but sometimes due to my schedule i can't read them all. Having a collection of my favorite to-read books in one section would be very helpful.

**Comment by maneprajakta** [comment]
Hi, @Mirnalin  I have edited your feature request description please follow it accordingly and make changes to it.
Also while creating an issue please follow the Issue template.
Also, go through our  [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) :smiley: it will help you in getting started with project .

**Comment by Mirnalin** [comment]
> Hi, @Mirnalin I have edited your feature request description please follow it accordingly and make changes to it.
> Also while creating an issue please follow the Issue template.
> Go through our [Starter Guide](https://github.com/Praful932/Kitabe/discussions/42) 😃 it will help you in getting started with project .

**Comment by Mirnalin** [comment]
@maneprajakta Hey! I have edited the comment and elaborated this issue and also let know if you want any more changes to it. I will like to solve this issue. Please assign this to me. And add GsSOC'21 label.

**Comment by maneprajakta** [comment]
@Mirnalin have you thought about how you will be implementing this, can you elaborate?

**Comment by maneprajakta** [comment]
@Mirnalin any updates ?

**Comment by anjali494** [comment]
@maneprajakta I am a GSSOC'21 participant and i would like to work on this feature. Can you please assign this to me?
I plan to do the following to implement this feature:
1. add a wishlist button on the header
2. add a 'add to wishlist' button on the dialogue box that appears after clicking on 'More Details'.

**Comment by Mirnalin** [comment]
@maneprajakta I'll be adding a save for later button along with "more details" and "rate this book" buttons.
Along with it I'll add a wishlist button (to check out the list of saved books) in the header.

**Comment by Praful932** [comment]
@Mirnalin wouldn't the intention/functionality of save for later & wishlist button almost be the same?

**Comment by Mirnalin** [comment]
yep, i was just using the two phrases for the same thing  @Praful932

**Comment by Praful932** [comment]
Alright, we can have a wishlist button button in the modal that comes up from search, It would be nice if you could make a mockup of the modal UI that you wish to make, you'll also have to make necessary modal connected with user in backend and also a separate page for the same
@maneprajakta what do you think should we keep a separate page for this or put it into Library which is being created by #64 
then we should make a new issue for the page after that issue is finished

**Comment by maneprajakta** [comment]
@Praful932 separate page would be better as #64 is for books which are rated by the user but wishlist is something which user wants to read.

**Comment by Fairspy** [comment]
@Praful932 @maneprajakta  I actually have a suggestion for this we could add two buttons below the library heading with read and saved for later and with javascript we can make it so that clicking on one would show that part of the html file as I was thinking having too many links on the header would make it feel crowded.

**Comment by Mirnalin** [comment]
@Praful932  @maneprajakta  so assign it to me as GSSoC'21 participant.

**Comment by Praful932** [comment]
Agree with @Fairspy You can add `Read` & `Saved`, and clicking on them, would lead to respective pages, @Mirnalin you can make it similar what is being done in #64

**Comment by maneprajakta** [comment]
@Mirnalin any updates?

**Comment by SalmaZakaria** [comment]
@Mirnalin Could you assign this issue to me please?

**Comment by maneprajakta** [comment]
@SalmaZakaria you can go ahead with this . Before that, if you could explain how you aim to do this?

**Comment by Mirnalin** [comment]
@maneprajakta i'm working on it, it will take a while

**Comment by Praful932** [comment]
> @Mirnalin any updates?

@Mirnalin Since there was no response so we had to unassign you
@SalmaZakaria There's an ongoing feature #100 , and we would like it to all come under library, clicking on library will have two options already read books & wishlist, and clicking on any of them will redirect to that page.
You can elaborate your implementation details so we know you're on the same page

**Comment by Mirnalin** [comment]
@Praful932 sorry actually due to some mishappening in the family I couldn't update. 
I'm working on it, please assign it to me again.

**Comment by Praful932** [comment]
> @Praful932 sorry actually due to some mishappening in the family I couldn't update.
> I'm working on it, please assign it to me again.

Sorry to hear that, Hope you're well. Due to the nature of open source, the issues are assigned on a FCFS basis, and since no one was assigned, the issue was up for grab. There are a lot of [unassigned issues](https://github.com/Praful932/Kitabe/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee) that you can take up. And we are happy to answer any doubts, you can open up a new discussion in the [forum ](https://github.com/Praful932/Kitabe/discussions/new)or connect with us on discord.
Thanks

**Comment by SalmaZakaria** [comment]
@Mirnalin How can I go ahead without assigning it to me?
Is this Possible?

**Comment by SalmaZakaria** [comment]
@Praful932 I will add a page with Cards containers wished books only and I haven't found this on issue #100 
So Can you assign this to me to start implementing it?

**Comment by Praful932** [comment]
Assigned you @SalmaZakaria 
You can implement a similar page as #100 , and link in dropdown when Library is clicked, one would be Wishlist and another would be Your books. Check the PR associated with that issue for more details

**Comment by SalmaZakaria** [comment]
@Praful932 After I had cloned the repository to my local machine I don't know how to see my changes when I click on any HTML page it opens with Html only without CSS

**Comment by Praful932** [comment]
@SalmaZakaria Head to project discord

**Comment by Praful932** [comment]
@SalmaZakaria Any updates? You can open a WIP/Draft PR so we can track that you are going in the right direction :)

**Comment by maneprajakta** [comment]
@SalmaZakaria any updates?

**Comment by SalmaZakaria** [comment]
@Praful932  @maneprajakta I am very sorry for the late reply
I am working on it now

**Comment by maneprajakta** [comment]
@SalmaZakaria you can draft a wip pr for changes done till now

**Comment by Praful932** [comment]
@SalmaZakaria Any updates?

**Comment by Fairspy** [comment]
@Praful932 @maneprajakta Can I work on this?

**Comment by Fairspy** [comment]
@Praful932 @maneprajakta Can I work on this?

**Comment by maneprajakta** [comment]
@Fairspy Yes go for it.

**Comment by Fairspy** [comment]
Great then I'll start working on it!
@maneprajakta I would just like to ask one thing do you guys want the save for later button on the book card or in the book modal?

**Comment by Praful932** [comment]
Just Book modal should be fine for now

**Comment by maneprajakta** [comment]
@Fairspy any updates?

**Comment by Fairspy** [comment]
@maneprajakta I am basically done will open a PR by today or for sure tomorrow.
