### ISSUE TITLE
Brand-logo on the navbar

### ISSUE THREAD

**Issue by SandeepKrSuman** [Praful932/Kitabe#58]
**Is your feature request related to a problem? Please describe.**
Navbar contain brand name as a simple text. Having a brand image instead of simple text would look better.

**Describe the solution you'd like**
Adding the logo as the brand-image.

**Are you willing to contribute to this issue?** [Yes/No]
Yes, I want to contribute to this issue as a part of GSSOC'21.

**Additional context**
- Before change: 
![Screenshot (240)](https://user-images.githubusercontent.com/54541515/110633245-8afcc700-81ce-11eb-8e49-08b30a07c9c9.png)

- After change: 
![Screenshot (241)](https://user-images.githubusercontent.com/54541515/110633283-964ff280-81ce-11eb-95ea-38609bffc00e.png)

**Comment by thesakshipandey** [comment]
Yes, I want to contribute to this issue as a part of GSSOC'21.

**Comment by anshika208** [comment]
Yes , i want to contribute to this issue as a part of GSSOC'21

**Comment by Praful932** [comment]
@SandeepKrSuman Good catch! You can take it up. Follow the important points in the [guidelines](https://github.com/Praful932/Kitabe/discussions/42),
Happy hacking!

@thesakshipandey @anshika208 Since this issue is taken up you can have a look at the [guidelines](https://github.com/Praful932/Kitabe/discussions/42)

**Comment by SandeepKrSuman** [comment]
oh m so sorry. By mistake I clicked on "close this" . what to do now please help @Praful932
